apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: pool-coordinator
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: Cg==
    service:
      name: pool-coordinator-webhook
      namespace: {{ .Release.Namespace }}
      path: /pool-coordinator-webhook-validate
  failurePolicy: Fail
  name: vpoolcoordinator.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - pods
  sideEffects: None

