{{- if and .Values.admissionWebhooks.enabled .Values.admissionWebhooks.patch.enabled (not .Values.admissionWebhooks.certManager.enabled) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pool-coordinator-admission
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: pool-coordinator-admission
    helm.sh/chart: pool-coordinator-0.1.0
    app.kubernetes.io/name: pool-coordinator
    app.kubernetes.io/instance: pool-coordinator
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pool-coordinator-admission
subjects:
  - kind: ServiceAccount
    name: pool-coordinator-admission
    namespace: {{ .Release.Namespace }}
{{- end }}
