{{- if and .Values.admissionWebhooks.enabled .Values.admissionWebhooks.patch.enabled (not .Values.admissionWebhooks.certManager.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  pool-coordinator-admission
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: pool-coordinator-admission
    helm.sh/chart: pool-coordinator-0.1.0
    app.kubernetes.io/name: pool-coordinator
    app.kubernetes.io/instance: pool-coordinator
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
{{- end }}
